#!/bin/sh

basedir=$(dirname "$(readlink -f "$0")")
desktopfiles="$basedir"/desktopfiles

[ -d $desktopfiles ] || mkdir $desktopfiles
rm -f $desktopfiles/*

deleted_commands=$(python "$basedir"/create-desktop-files.py)
[ -z "$deleted_commands" ] || xdg-desktop-menu uninstall --noupdate $deleted_commands

xdg-desktop-menu install "$basedir"/command-menu.directory "$desktopfiles"/*.desktop
